name: Deploy to Raspberry Pi -- bmcc81

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          sudo mkdir -p /etc/cloudflared
          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Configure SSH for Cloudflare Tunnel
        env:
          DEPLOY_HOST: rpi-ssh.webinkgraphics.com
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/config
          Host rpi
            HostName $DEPLOY_HOST
            User deploy
            ProxyCommand "cloudflared access ssh --hostname %h"
            IdentityFile ~/.ssh/id_rsa
          EOF
                    chmod 600 ~/.ssh/config

      - name: Deploy via rsync over Cloudflare Tunnel
        run: |
          rsync -avz \
            -e "ssh -F ~/.ssh/config" \
            ./ rpi:/var/www/php-site
